### ISSUE TITLE
Memory leaks in tests

### ISSUE THREAD

**Issue by masterleinad** [boostorg/serialization#76]
Compiling with `-fsanitize=address` reports memory leaks similar to
```
 Direct leak of 160 byte(s) in 1 object(s) allocated from:
     #0 0x7f29c482d9c0 in operator new(unsigned long) ../../.././libsanitizer/asan/asan_new_delete.cc:80
     #1 0x466293 in boost::archive::detail::heap_allocation<J>::doesnt_have_new_operator::invoke_new() (/mnt/data/darndt/boost-develop/bin.v2/libs/serialization/test/   test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/threadapi-pthread/test_cyclic_ptrs_text_warchive+0x466293)
     #2 0x465202 in boost::archive::detail::heap_allocation<J>::invoke_new() (/mnt/data/darndt/boost-develop/bin.v2/libs/serialization/test/                             test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/threadapi-pthread/test_cyclic_ptrs_text_warchive+0x465202)
     #3 0x463876 in boost::archive::detail::heap_allocation<J>::heap_allocation() (/mnt/data/darndt/boost-develop/bin.v2/libs/serialization/test/                        test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/threadapi-pthread/test_cyclic_ptrs_text_warchive+0x463876)
     #4 0x46247b in boost::archive::detail::pointer_iserializer<boost::archive::text_wiarchive, J>::heap_allocation() const (/mnt/data/darndt/boost-develop/bin.v2/libs/ serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/threadapi-pthread/test_cyclic_ptrs_text_warchive+0x46247b)
     #5 0x7f29c4079b92 in boost::archive::detail::basic_iarchive_impl::load_pointer(boost::archive::detail::basic_iarchive&, void*&, boost::archive::detail::            basic_pointer_iserializer const*, boost::archive::detail::basic_pointer_iserializer const* (*)(boost::serialization::extended_type_info const&)) (/mnt/data/darndt/     boost-develop/bin.v2/libs/serialization/build/gcc-gnu-7.2.0/debug/threadapi-pthread/libboost_serialization.so.1.66.0+0xa0b92)
     #6 0x7f29c4078655 in boost::archive::detail::basic_iarchive::load_pointer(void*&, boost::archive::detail::basic_pointer_iserializer const*, boost::archive::        detail::basic_pointer_iserializer const* (*)(boost::serialization::extended_type_info const&)) ../../../libs/serialization/src/basic_iarchive.cpp:573
     #7 0x4242c6 in void boost::archive::detail::load_pointer_type<boost::archive::text_wiarchive>::invoke<J*>(boost::archive::text_wiarchive&, J*&) (/mnt/data/darndt/  boost-develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/threadapi-pthread/test_cyclic_ptrs_text_warchive+0x4242c6)
     #8 0x423a69 in void boost::archive::load<boost::archive::text_wiarchive, J*>(boost::archive::text_wiarchive&, J*&) (/mnt/data/darndt/boost-develop/bin.v2/libs/     serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/threadapi-pthread/test_cyclic_ptrs_text_warchive+0x423a69)
     #9 0x423694 in void boost::archive::detail::common_iarchive<boost::archive::text_wiarchive>::load_override<J*>(J*&) (/mnt/data/darndt/boost-develop/bin.v2/libs/    serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/threadapi-pthread/test_cyclic_ptrs_text_warchive+0x423694)
     #10 0x4232c7 in void boost::archive::basic_text_iarchive<boost::archive::text_wiarchive>::load_override<J*>(J*&) (/mnt/data/darndt/boost-develop/bin.v2/libs/       serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/threadapi-pthread/test_cyclic_ptrs_text_warchive+0x4232c7)
     #11 0x422e89 in void boost::archive::text_wiarchive_impl<boost::archive::text_wiarchive>::load_override<J*>(J*&) (/mnt/data/darndt/boost-develop/bin.v2/libs/       serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/threadapi-pthread/test_cyclic_ptrs_text_warchive+0x422e89)
     #12 0x4227f4 in boost::archive::text_wiarchive& boost::archive::detail::interface_iarchive<boost::archive::text_wiarchive>::operator>><J*>(J*&) (/mnt/data/darndt/  boost-develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/threadapi-pthread/test_cyclic_ptrs_text_warchive+0x4227f4)
     #13 0x421f1d in void boost::serialization::nvp<J*>::load<boost::archive::text_wiarchive>(boost::archive::text_wiarchive&, unsigned int) (/mnt/data/darndt/boost-    develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/threadapi-pthread/test_cyclic_ptrs_text_warchive+0x421f1d)
     #14 0x421918 in void boost::serialization::access::member_load<boost::archive::text_wiarchive, boost::serialization::nvp<J*> >(boost::archive::text_wiarchive&,     boost::serialization::nvp<J*>&, unsigned int) (/mnt/data/darndt/boost-develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/   threadapi-pthread/test_cyclic_ptrs_text_warchive+0x421918)
     #15 0x421717 in boost::serialization::detail::member_loader<boost::archive::text_wiarchive, boost::serialization::nvp<J*> >::invoke(boost::archive::                text_wiarchive&, boost::serialization::nvp<J*>&, unsigned int) (/mnt/data/darndt/boost-develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-  gnu-7.2.0/debug/threadapi-pthread/test_cyclic_ptrs_text_warchive+0x421717)
     #16 0x4215c5 in void boost::serialization::split_member<boost::archive::text_wiarchive, boost::serialization::nvp<J*> >(boost::archive::text_wiarchive&, boost::    serialization::nvp<J*>&, unsigned int) (/mnt/data/darndt/boost-develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/          threadapi-pthread/test_cyclic_ptrs_text_warchive+0x4215c5)
     #17 0x421473 in void boost::serialization::nvp<J*>::serialize<boost::archive::text_wiarchive>(boost::archive::text_wiarchive&, unsigned int) (/mnt/data/darndt/     boost-develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/threadapi-pthread/test_cyclic_ptrs_text_warchive+0x421473)
     #18 0x42128c in void boost::serialization::access::serialize<boost::archive::text_wiarchive, boost::serialization::nvp<J*> >(boost::archive::text_wiarchive&,       boost::serialization::nvp<J*>&, unsigned int) (/mnt/data/darndt/boost-develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/   threadapi-pthread/test_cyclic_ptrs_text_warchive+0x42128c)
     #19 0x4210cb in void boost::serialization::serialize<boost::archive::text_wiarchive, boost::serialization::nvp<J*> >(boost::archive::text_wiarchive&, boost::       serialization::nvp<J*>&, unsigned int) (/mnt/data/darndt/boost-develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/          threadapi-pthread/test_cyclic_ptrs_text_warchive+0x4210cb)
     #20 0x420dd3 in void boost::serialization::serialize_adl<boost::archive::text_wiarchive, boost::serialization::nvp<J*> >(boost::archive::text_wiarchive&, boost::   serialization::nvp<J*>&, unsigned int) (/mnt/data/darndt/boost-develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/          threadapi-pthread/test_cyclic_ptrs_text_warchive+0x420dd3)
     #21 0x4208e3 in void boost::archive::detail::load_non_pointer_type<boost::archive::text_wiarchive>::load_only::invoke<boost::serialization::nvp<J*> >(boost::       archive::text_wiarchive&, boost::serialization::nvp<J*> const&) (/mnt/data/darndt/boost-develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc- gnu-7.2.0/debug/threadapi-pthread/test_cyclic_ptrs_text_warchive+0x4208e3)
     #22 0x420493 in void boost::archive::detail::load_non_pointer_type<boost::archive::text_wiarchive>::invoke<boost::serialization::nvp<J*> const>(boost::archive::    text_wiarchive&, boost::serialization::nvp<J*> const&) (/mnt/data/darndt/boost-develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.  0/debug/threadapi-pthread/test_cyclic_ptrs_text_warchive+0x420493)
     #23 0x420321 in void boost::archive::load<boost::archive::text_wiarchive, boost::serialization::nvp<J*> const>(boost::archive::text_wiarchive&, boost::             serialization::nvp<J*> const&) (/mnt/data/darndt/boost-develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/threadapi-        pthread/test_cyclic_ptrs_text_warchive+0x420321)
     #24 0x4201a2 in void boost::archive::detail::common_iarchive<boost::archive::text_wiarchive>::load_override<boost::serialization::nvp<J*> const>(boost::            serialization::nvp<J*> const&) (/mnt/data/darndt/boost-develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/threadapi-        pthread/test_cyclic_ptrs_text_warchive+0x4201a2)
     #25 0x41fc6b in void boost::archive::basic_text_iarchive<boost::archive::text_wiarchive>::load_override<boost::serialization::nvp<J*> const>(boost::serialization:: nvp<J*> const&) (/mnt/data/darndt/boost-develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/threadapi-pthread/               test_cyclic_ptrs_text_warchive+0x41fc6b)
     #26 0x41f0a7 in void boost::archive::text_wiarchive_impl<boost::archive::text_wiarchive>::load_override<boost::serialization::nvp<J*> const>(boost::serialization:: nvp<J*> const&) (/mnt/data/darndt/boost-develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/threadapi-pthread/               test_cyclic_ptrs_text_warchive+0x41f0a7)
     #27 0x41ddee in boost::archive::text_wiarchive& boost::archive::detail::interface_iarchive<boost::archive::text_wiarchive>::operator>><boost::serialization::nvp<J* > const>(boost::serialization::nvp<J*> const&) (/mnt/data/darndt/boost-develop/bin.v2/libs/serialization/test/test_cyclic_ptrs_text_warchive.test/gcc-gnu-7.2.0/debug/  threadapi-pthread/test_cyclic_ptrs_text_warchive+0x41ddee)
     #28 0x40e591 in test2() /mnt/data/darndt/boost-develop/libs/serialization/test/test_cyclic_ptrs.cpp:143
     #29 0x4105c0 in test_main(int, char**) /mnt/data/darndt/boost-develop/libs/serialization/test/test_cyclic_ptrs.cpp:199
```

**Comment by robertramey** [comment]
I merged in changes in tests so the -fsanitize=address should now report only relevant errors.
